// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjcs-9l_R5tKzLUopIOnXN8gdKsWNNMgE',
    appId: '1:695943159687:web:ef005c0454a5c211fafd22',
    messagingSenderId: '695943159687',
    projectId: 'apo-project-7388e',
    authDomain: 'apo-project-7388e.firebaseapp.com',
    databaseURL: 'https://apo-project-7388e-default-rtdb.firebaseio.com',
    storageBucket: 'apo-project-7388e.appspot.com',
    measurementId: 'G-92CZ22NYEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRzQcoGaeXNok-i7_C8QLYzBIfPeVetHs',
    appId: '1:695943159687:android:631a8bcf81e15643fafd22',
    messagingSenderId: '695943159687',
    projectId: 'apo-project-7388e',
    databaseURL: 'https://apo-project-7388e-default-rtdb.firebaseio.com',
    storageBucket: 'apo-project-7388e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjsW-nn0TuByztpB_6qHWgIyNJUdWfXsc',
    appId: '1:695943159687:ios:729d444ba6b1f055fafd22',
    messagingSenderId: '695943159687',
    projectId: 'apo-project-7388e',
    databaseURL: 'https://apo-project-7388e-default-rtdb.firebaseio.com',
    storageBucket: 'apo-project-7388e.appspot.com',
    iosClientId:
        '695943159687-0f626m9benod90dsg73aq6ijlfgnefge.apps.googleusercontent.com',
    iosBundleId: 'com.example.apoDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjsW-nn0TuByztpB_6qHWgIyNJUdWfXsc',
    appId: '1:695943159687:ios:729d444ba6b1f055fafd22',
    messagingSenderId: '695943159687',
    projectId: 'apo-project-7388e',
    databaseURL: 'https://apo-project-7388e-default-rtdb.firebaseio.com',
    storageBucket: 'apo-project-7388e.appspot.com',
    iosClientId:
        '695943159687-0f626m9benod90dsg73aq6ijlfgnefge.apps.googleusercontent.com',
    iosBundleId: 'com.example.apoDelivery',
  );
}
